import { createSlice } from '@reduxjs/toolkit';

// Helper to load cart from localStorage
const loadCartState = () => {
  try {
    const serializedState = localStorage.getItem('cartItems');
    if (serializedState === null) {
      return [];
    }
    return JSON.parse(serializedState);
  } catch (err) {
    console.error("Could not load cart from localStorage", err);
    return [];
  }
};

// Helper to save cart to localStorage
const saveCartState = (items) => {
  try {
    const serializedState = JSON.stringify(items);
    localStorage.setItem('cartItems', serializedState);
  } catch (err) {
    console.error("Could not save cart to localStorage", err);
  }
};

/**
 * Redux Slice for managing Shopping Cart State.
 * Demonstrates: Core Redux, Action Creators (generated by createSlice).
 */
export const cartSlice = createSlice({
  name: 'cart',
  initialState: {
    items: loadCartState(),
    loading: false
  },
  reducers: {
    addToCart: (state, action) => {
      const existing = state.items.find(item => item.id === action.payload.id);
      if (existing) {
        existing.quantity += (action.payload.quantity || 1);
      } else {
        state.items.push({ ...action.payload, quantity: action.payload.quantity || 1 });
      }
      saveCartState(state.items);
    },
    updateQuantity: (state, action) => {
      const { id, amount } = action.payload;
      const existing = state.items.find(i => i.id === id);
      if (existing) {
        existing.quantity += amount;
        if (existing.quantity <= 0) {
          state.items = state.items.filter(i => i.id !== id);
        }
        saveCartState(state.items);
      }
    },
    removeFromCart: (state, action) => {
      state.items = state.items.filter(item => item.id !== action.payload.id);
      saveCartState(state.items);
    },
    clearCart: (state) => {
      state.items = [];
      saveCartState(state.items);
    },
    /**
     * validateCartItems: High-performance sync with catalog.
     * Uses Map for O(1) lookups to avoid lag with large catalogs.
     */
    validateCartItems: (state, action) => {
      const catalogItems = action.payload; // Expected to be an array of products
      if (!catalogItems || catalogItems.length === 0) return;

      // 1. Convert Catalog to a Map for O(1) performance
      const catalogMap = new Map(catalogItems.map(p => [String(p.id), p]));

      let hasChanges = false;
      let priceChanged = false;

      state.items = state.items.map(item => {
        const catalogItem = catalogMap.get(String(item.id));

        if (!catalogItem) {
          // Item no longer exists in DB
          if (!item.isUnavailable) hasChanges = true;
          return { ...item, isUnavailable: true };
        }

        const updatedItem = { ...item };
        
        // Clear unavailable flag if it was set before
        if (updatedItem.isUnavailable) {
          updatedItem.isUnavailable = false;
          hasChanges = true;
        }

        // 2. Check Price Sync (Silent update with flag)
        const currentPrice = parseFloat(catalogItem.price);
        if (item.price !== currentPrice) {
          updatedItem.price = currentPrice;
          updatedItem.priceChanged = true;
          priceChanged = true;
          hasChanges = true;
        }

        // 3. Check Stock Sync
        const isOutOfStock = catalogItem.stock <= 0;
        if (item.isOutOfStock !== isOutOfStock) {
          updatedItem.isOutOfStock = isOutOfStock;
          hasChanges = true;
        }

        return updatedItem;
      });

      if (hasChanges) {
        state.hasValidationAlerts = true;
        state.priceChangedGlobal = priceChanged;
        saveCartState(state.items);
      }
    },
    clearValidationAlerts: (state) => {
      state.hasValidationAlerts = false;
      state.priceChangedGlobal = false;
    }
  }
});

// Export Action Creators
export const { 
  addToCart, 
  removeFromCart, 
  clearCart, 
  updateQuantity, 
  validateCartItems, 
  clearValidationAlerts 
} = cartSlice.actions;

// Export default Reducer
export default cartSlice.reducer;
